openapi: 3.0.0
info:
  description: API Public Template Rudi
  version: 0.0.1
  title: rudi-template-api
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: ca.marchand@rennesmetropole.fr
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths: {}
components:
  schemas:
    SearchItemInfo:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/SearchType'
        name:
          type: string
        url:
          type: string
        image_url:
          type: string
      discriminator:
        propertyName: type
        mapping:
          dataset: '#/components/schemas/SearchDatasetInfo'
          dataverse: '#/components/schemas/SearchDataverseInfo'
    SearchType:
      type: string
      enum:
        - dataset
        - dataverse
    SearchDatasetInfo:
      allOf:
        - $ref: '#/components/schemas/SearchItemInfo'
        - type: object
          properties:
            global_id:
              type: string
            description:
              type: string
            published_at:
              type: string
              format: date-time
            publisher:
              type: string
            name_of_dataverse:
              type: string
            subjects:
              type: array
              items:
                type: string
            fileCount:
              type: integer
            authors:
              type: array
              items:
                type: string
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
            contacts:
              type: array
              items:
                $ref: '#/components/schemas/SearchContactInfo'
    SearchDataverseInfo:
      allOf:
        - $ref: '#/components/schemas/SearchItemInfo'
        - type: object
          properties:
            identifier:
              type: string
            description:
              type: string
            published_at:
              type: string
              format: date-time
    SearchContactInfo:
      type: object
      properties:
        name:
          type: string
        affiliation:
          type: string
    Identifier:
      type: object
      properties:
        id:
          type: integer
          format: int64
        persistentId:
          type: string
    MessageResponse:
      type: object
      properties:
        message:
          type: string
    Dataset:
      allOf:
        - $ref: '#/components/schemas/Identifier'
        - type: object
          properties:
            identifier:
              type: string
            protocol:
              type: string
            authority:
              type: string
            persistentUrl:
              type: string
            publisher:
              type: string
            publicationDate:
              type: string
              format: date
            datasetVersion:
              $ref: '#/components/schemas/DatasetVersion'
            latestVersion:
              $ref: '#/components/schemas/DatasetVersion'
    DatasetVersion:
      type: object
      properties:
        id:
          type: integer
          format: int64
        datasetId:
          type: integer
          format: int64
        datasetPersistentId:
          type: string
        versionState:
          type: string
        createTime:
          type: string
          format: date-time
        lastUpdateTime:
          type: string
          format: date-time
        versionNumber:
          type: integer
        versionMinorNumber:
          type: integer
        metadataBlocks:
          $ref: '#/components/schemas/DatasetMetadataBlock'
    DatasetMetadataBlock:
      type: object
      properties:
        citation:
          $ref: '#/components/schemas/DatasetMetadataBlockElement'
        rudi:
          $ref: '#/components/schemas/DatasetMetadataBlockElement'
    DatasetMetadataBlockElement:
      type: object
      properties:
        displayName:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/DatasetMetadataBlockElementField'
    DatasetMetadataBlockElementField:
      type: object
      properties:
        typeName:
          type: string
        typeClass:
          $ref: '#/components/schemas/FieldTypeClass'
        multiple:
          type: boolean
        value:
          type: object
    FieldTypeClass:
      type: string
      enum:
        - primitive
        - compound
        - controlledVocabulary
    #---------------------------------------------------------------------------
    MetadataList:
      type: object
      properties:
        total:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: './RUDI-PRODUCER.yml#/components/schemas/Metadata'
    #---------------------------------------------------------------------------
    MetadataListFacets:
      type: object
      properties:
        metadataList:
          $ref: '#/components/schemas/MetadataList'
        facets:
          $ref: '#/components/schemas/MetadataFacets'
    #---------------------------------------------------------------------------
    MetadataFacets:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/MetadataFacet'
    #---------------------------------------------------------------------------
    MetadataFacet:
      type: object
      properties:
        propertyName:
          type: string
        values:
          type: array
          items:
            $ref: '#/components/schemas/MetadataFacetValues'
    #---------------------------------------------------------------------------
    MetadataFacetValues:
      type: object
      properties:
        value:
          type: string
        count:
          type: integer
    #---------------------------------------------------------------------------
    DatasetSize:
      description: Indicative size of the data
      type: object
      properties:
        #......................
        numbers_of_records:
          type: integer
          minimum: 0
        #......................          
        number_of_fields:
          type: integer
          minimum: 0

    #---------------------------------------------------------------------------
    DatasetSearchCriteria:
      description: Critère de recherche dans le dataset, notamment dans ses métadonnées
      type: object
      properties:
        globalIds:
          description: Identifiants des jeux de données basés sur le datasetField global_id
          type: array
          items:
            type: string
            format: uuid
        limit:
          type: integer
          description: Nombre d'élément maximum
        offset:
          type: integer
          description: Index de l'élément initial
        freeText:
          description: texte libre présent dans le titre ou dans le synopsis du jeu de données
          type: string
        keywords:
          description: Mots clés du jeu de données
          type: array
          items:
            type: string
        themes:
          description: Liste de thèmes (le thème du jeu de données doit correspondre à l'un de ces thèmes)
          type: array
          items:
            type: string
        producerNames:
          description: Liste de noms de producteurs (le nom du producteur du jeu de données doit correspondre à l'un de ces noms)
          type: array
          items:
            type: string
        dateDebut:
          description: Période temporelle min (temporal_spread.start_date)
          type: string
          format: date-time
        dateFin:
          description: Période temporelle max (temporal_spread.end_date)
          type: string
          format: date-time
        order:
          description: 'Liste des tris à réaliser. Valeurs possibles :  name, date, title, producername, updatedate. Mettre un signe - devant pour tri descendant (ex -name)'
          type: string
        orderByScoreOfKeywords:
          description: Ordonne les résultats pour avoir en premier les JDD avec le plus de mots-clés en commun avec le critère keywords. Les JDD sans mots-clés en commun sont quand même listés mais en dernier.
          type: boolean
          default: false
        restrictedAccess:
          description: Données ouvertes (false) ou restreintes (true)
          type: boolean
        doi:
          $ref: 'RUDI-PRODUCER.yml#/components/schemas/DOI'
        localId:
          type: string
          description: Identifiant du jeu de données chez le producteur de données
          example: 2020.11-Laennec-AQMO-air quality sensors measures
