spring:
  application:
    name: rudi-apigateway
  cloud:
    gateway.server.webflux:
      routes:
        - id: test
          uri: https://www.google.fr
          predicates:
            - Path=/google
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
