spring:
  application:
    name: rudi-apigateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: https://www.google.fr
          predicates:
            - Path=/google
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
          
springdoc:
  enable-native-support: true
  api-docs:
    groups:
      enabled: true
    enabled: true
  group-configs:
    - group: open-api
      paths-to-match:
        - /apigateway/v1/**
      display-name: ApiGateway API
  swagger-ui:
    config-url: /apigateway/v3/api-docs/swagger-config
    url: /apigateway/v3/api-docs
    urls:
      - url: /apigateway/v3/api-docs
        name: Internal api
            